[client]
showErrorDetails = true

[theme]
base="light"
primaryColor="#2E6AE6"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F6F8FB"
textColor="#0F172A"

[server]
headless = true
enableCORS = false
